---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: wordpress-server
  remote_user: vagrant
  become: yes
  # remote_user: user
  become_method: sudo

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
